# Generated by Django 4.2.7 on 2025-07-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('internship', 'Internship'), ('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract')], max_length=20)),
                ('stipend_salary', models.CharField(blank=True, max_length=100)),
                ('application_deadline', models.DateField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('number_of_openings', models.PositiveIntegerField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='accounts.providerprofile')),
            ],
        ),
    ]
