# Generated by Django 4.2.7 on 2025-08-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementrequest',
            name='provider_comments',
            field=models.TextField(blank=True, help_text='Comments from provider during approval/rejection'),
        ),
        migrations.AddField(
            model_name='placementrequest',
            name='tutor_comments',
            field=models.TextField(blank=True, help_text='Comments from tutor during approval/rejection'),
        ),
    ]
